framework:
  secret: '%env(APP_SECRET)%'
  templating:
    engines: ['twig']
  session:
    handler_id: ~
  php_errors:
    log: true
    throw: '%kernel.debug%'
  cache:
    prefix_seed: alcohol/eve-assets

