version: '3.7'

services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: eve-assets-nginx
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.backend: eve-assets-nginx
      traefik.frontend.rule: "Host:eveassets.localhost"
      traefik.port: 8000
    depends_on:
    - php-fpm
    networks:
    - traefik
    - default

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: eve-assets-fpm
    user: $DOCKER_UID:$DOCKER_GID
    environment:
    - APP_ENV=dev
    - APP_DEBUG=1
    - APP_SECRET=not-so-secret
    - EVE_CLIENT_ID=e39201af27124b50ae81d19629100a53
    - EVE_CLIENT_SECRET=baDlVrjPUh58FQXDYZSV9c0jZ7vcNScnxuNYWLOe
    - EVE_CALLBACK_URL=http://eveassets.localhost/security/check
    - EVE_ESI_URI=https://esi.evetech.net
    working_dir: /srv
    volumes:
    - .:/srv
    networks:
      default:
        aliases:
        - fcgi

networks:

  default:

  traefik:
    external: true
