security:

  providers:
    users:
      id: 'user.provider'

  firewalls:
    assets:
      pattern: '^/(_(profiler|wdt)|css|images|js)/'
      anonymous: ~
      security: false
    oauth2:
      pattern: '^/'
      anonymous: ~
      logout:
        path: '/security/logout'
        invalidate_session: true
        success_handler: 'security.logout_handler'
      guard:
        authenticators:
          - 'security.oauth2_guard'

  access_control:
    - { path: '^/security/', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
    - { path: '^/test', roles: 'IS_AUTHENTICATED_ANONYMOUSLY' }
    - { path: '^/', roles: 'ROLE_USER' }
