monolog:
    handlers:
        main:
            type: whatfailuregroup
            members: ['file', 'stdout']
        file:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        stdout:
            type: stream
            path: /tmp/stdout
            level: debug
