parameters:
  paste.ttl: 3600

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Doctrine\Common\Cache\FilesystemCache:
    arguments: ['%kernel.cache_dir%/data']

  Doctrine\Common\Cache\Cache: '@Doctrine\Common\Cache\FilesystemCache'
