#!/usr/bin/env bash

test -n "$TRAVIS_COMMIT" || { echo "Missing TRAVIS_COMMIT value" >&2; exit 1; }
test -n "$DOCKERHUB_USERNAME" || { echo "Missing DOCKERHUB_USERNAME value" >&2; exit 1; }
test -n "$DOCKERHUB_PASSWORD" || { echo "Missing DOCKERHUB_PASSWORD value" >&2; exit 1; }

echo "$DOCKERHUB_PASSWORD" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin

docker build --file=docker/services/nginx/Dockerfile --tag=alcohol/eve-nginx:latest .
docker build --file=docker/services/php-fpm/Dockerfile.dist --tag=alcohol/eve-fpm:latest --build-arg=RELEASE=$(git rev-parse --short "$TRAVIS_COMMIT") .

docker push alcohol/eve-nginx:latest
docker push alcohol/eve-fpm:latest

docker logout
